#@ load("@ytt:data", "data")

#@ deployments = ["infra"]

#@ def pipeline_image():
#@   return data.values.docker_registry + "/release-pipeline"
#@ end

#@ def task_image_config():
type: registry-image
source:
  username: #@ data.values.docker_registry_user
  password: #@ data.values.docker_registry_password
  repository: #@ pipeline_image()
#@ end

#@ def cepler_config(deployment):
#@   return "cepler/" + deployment + ".yml"
#@ end

#@ def cepler_resource_name(deployment):
#@   return deployment + "-in"
#@ end

#@ def cepler_in(deployment):
name: #@ cepler_resource_name(deployment)
type: cepler-in
source:
  uri: #@ data.values.deployments_git_uri
  branch: #@ data.values.deployments_git_branch
  private_key: #@ data.values.github_private_key
  environment: #@ data.values.release_environment
  config: #@ cepler_config(deployment)
#@ end

groups:
#@ for depl in deployments:
- name: #@ depl
  jobs:
  - #@ depl + "-release"
#@ end
- name: image
  jobs:
  - build-release-pipeline-image
- name: all
  jobs:
#@ for depl in deployments:
  - #@ depl + "-release"
#@ end
  - build-release-pipeline-image

jobs:
- name: infra-release
  plan:
  - in_parallel:
    - { get: infra-in, trigger: true }
    - { get: infra-version }
    - { get: repo }
    - { get: infra-repo }
    - { get: infra-repo-stable }
  - task: gen-changelog
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: infra-in
      - name: repo
      - name: infra-repo
      outputs:
      - name: changelog
      run:
        path: repo/ci/tasks/gen-changelog-infra.sh
  - task: bump-version
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: repo
      - name: changelog
      - name: infra-version
        path: version
      outputs:
      - name: infra-version
        path: version
      run:
        path: repo/ci/tasks/bump-version.sh
  - put: infra-repo-stable
    params:
      repository: infra-repo-stable
      tag: infra-version/version
      tag_prefix: v
  - task: prep-release-source
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: repo
        path: source-repo
      - name: changelog
      - name: infra-version
        path: version
      outputs:
      - name: gh-release
      run:
        path: repo/ci/tasks/prep-release-source.sh
  - put: github-release-infra
    params:
      name: gh-release/name
      tag: gh-release/tag
      body: gh-release/notes.md
  - task: update-meta-release
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: repo
      - name: changelog
      - name: infra-version
        path: version
      outputs:
      - name: repo
      run:
        path: repo/ci/tasks/update-meta-release.sh
  - put: infra-version
    params: { file: infra-version/version }
  - put: repo
    params:
      repository: repo
      branch: #@ data.values.git_branch
      rebase: true

- name: build-release-pipeline-image
  serial: true
  plan:
  - get: release-pipeline-image-def
    trigger: true
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: release-pipeline-image-def
      outputs:
      - name: image
      params:
        CONTEXT: release-pipeline-image-def/ci/image
      run:
        path: build
  - put: release-pipeline-image
    params:
      image: image/image.tar

resources:
- name: infra-repo
  type: git
  source:
    uri: #@ data.values.infra_git_uri
    branch: #@ data.values.infra_git_branch
    private_key: #@ data.values.github_private_key

- name: infra-repo-stable
  type: git
  source:
    uri: #@ data.values.infra_git_uri
    branch: #@ data.values.stable_git_branch
    private_key: #@ data.values.github_private_key

- name: github-release-infra
  type: github-release
  source:
    owner: #@ data.values.gh_org
    repository: #@ data.values.infra_gh_repo
    access_token: #@ data.values.github_api_token

- name: infra-version
  type: semver
  source:
    initial_version: 0.1.0
    driver: git
    file: infra-version
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_version_branch
    private_key: #@ data.values.github_private_key

- name: repo
  type: git
  source:
    paths: 
    - "template.md"
    - "release.yml"
    - "ci/tasks/*"
    - "config.toml"
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key
  
- name: release-pipeline-image
  type: registry-image
  source:
    tag: latest
    username: #@ data.values.docker_registry_user
    password: #@ data.values.docker_registry_password
    repository: #@ pipeline_image()

- name: release-pipeline-image-def
  type: git
  source:
    paths: [ci/image/Dockerfile]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key

#@ for depl in deployments:
- #@ cepler_in(depl)
#@ end

resource_types:
- name: cepler-in
  type: registry-image
  source:
    repository: cepler/cepler-concourse-resource
    tag: latest
