#@data/values
---
git_uri: git@github.com:GaloyMoney/meta-release.git
git_branch: main
pipeline_git_branch: main
github_private_key: ((github.private_key))
github_api_token: ((github.api_token))

gh_org: GaloyMoney
git_version_branch: versions
stable_git_branch: stable
src_repo_git_uri_prefix: git@github.com:GaloyMoney

docker_registry: us.gcr.io/galoy-org
docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))

deployments_git_uri: git@github.com:GaloyMoney/galoy-deployments.git
deployments_git_branch: main

infra_gh_repo: galoy-infra
infra_git_uri: git@github.com:GaloyMoney/galoy-infra.git
infra_git_branch: main

charts_gh_repo: charts
charts_git_uri: git@github.com:GaloyMoney/charts.git
charts_git_branch: main
charts_gh_pages_branch: gh-pages

mobile_gh_repo: galoy-mobile
